### ISSUE TITLE
Feature Request: destinationpath parameter

### ISSUE THREAD

**Issue by dmr** [maxharp3r/archive-rotator#3]
I have the archive_rotator file in my python package and now I want to rotate the file that some script put into /tmp/ --> running archive_rotator puts the rotated files into the current directory.

Maybe I just don't understand how to use the arguments, but how do I configure archive-rotator to put the result files into a specific location?

**Comment by dmr** [comment]
I want to do something like

```
python3 archive_rotator.py -n 5 --ext .xz --destinationpath myarchive/ bla.dump.xz
```

bla.dump.xz is in the same directory and it should be moved to myarchive/.

**Comment by maxharp3r** [comment]
I put this feature in (`--destination-dir`), thanks for the feedback. Notice that I've changed how you install archive-rotator (changed over to the standard pypi install).

**Comment by dmr** [comment]
Thank you :)
