### ISSUE TITLE
backup rotation with timestamp in filename

### ISSUE THREAD

**Issue by sgalam** [maxharp3r/archive-rotator#4]
Hello, 
I'm searching a solution for rotate backup files with a tiered/gfs logic and found your archive-rotator.
I have backup files with timestamp into filename so it's impossible to rotate them as all files have different name.
example:
vzdump-qemu-103-2016_09_24-01_25_13.vma.lzo
vzdump-qemu-103-2016_09_23-01_25_13.vma.lzo
vzdump-qemu-103-2016_09_22-01_25_13.vma.lzo

Do you see solutions for workaround this or the only way it's to rename/produce backups/logs file without the timestamp in the filename?

Thanks!

Matteo

**Comment by maxharp3r** [comment]
You could use archive-rotator, the downside is that you'll just have to send in a different file name each time, and you'll have to live with file names that contain two different timestamps.

I'd certainly be open to a pull request that adds a command line parameter to turn off the "add timestamp to the file name" feature -- that part of the file name is not required for the rotation algorithm.
